{-# OPTIONS --safe --without-K #-}
-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
--
-- GENERATED by echo-boundary (boundary.mjs). Do not edit by hand.
--
-- This module certifies an @boundary encoding-faithfulness verdict for a
-- concrete host-value -> integer-code table, by reusing the
-- EchoEncodingFaithfulness framework. It follows the SHAPE of that module's
-- worked Rank / rankCode / rankCode-injective instance.
--
-- Source table (host name -> code):
--   {
--     "crypto": 2,
--     "vector": 4,
--     "maths": 4,
--     "io": 1,
--     "neural": 4,
--     "quantum": 3,
--     "physics": 4,
--     "audio": 4,
--     "tensor": 4,
--     "graphics": 5
--   }

module KernelRouteBoundary where

open import Echo                   using (Echo)
open import EchoImageFactorization using (Injective)
open import EchoEncodingFaithfulness using (Encoding; module EncodingTheorems)

open import Data.Nat.Base         using (ℕ)
open import Data.Product.Base     using (Σ; _,_; _×_; proj₁)
open import Relation.Binary.PropositionalEquality
                                  using (_≡_; _≢_; refl)
open import Relation.Nullary      using (¬_)


-- The host-side enumerated value (one constructor per table name).
--   c0 = crypto
--   c1 = vector
--   c2 = maths
--   c3 = io
--   c4 = neural
--   c5 = quantum
--   c6 = physics
--   c7 = audio
--   c8 = tensor
--   c9 = graphics
data Host : Set where
  c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 : Host

-- The integer code the pure kernel computes on.
code : Host → ℕ
code c0 = 2
code c1 = 4
code c2 = 4
code c3 = 1
code c4 = 4
code c5 = 3
code c6 = 4
code c7 = 4
code c8 = 4
code c9 = 5

encoding : Encoding
encoding = record
  { Source = Host
  ; Code   = ℕ
  ; enc    = code
  }

module Theorems = EncodingTheorems encoding

-- The collision, as data: two distinct host values collapse onto the
-- same code 4.
--   c1 = vector
--   c2 = maths
-- Distinctness is constructor disjointness; the shared code is refl.
c1≢c2 : c1 ≢ c2
c1≢c2 ()

collision : c1 ≢ c2 × code c1 ≡ code c2
collision = c1≢c2 , refl

-- THE VERDICT, certified: the boundary exhibits controlled loss.
-- The colliding fibre admits NO section -- there is no pure
-- decode : ℕ → Host recovering the host value from its code,
-- because two distinct host values share one code. The lost
-- distinction is named and localised at code 4.
boundary-controlled-loss :
  ¬ Σ (ℕ → Host) (λ decode → ∀ x → decode (code x) ≡ x)
boundary-controlled-loss =
  Theorems.encoding-collision⇒no-section
    c1 c2
    c1≢c2
    refl

