{-# OPTIONS --safe --without-K #-}
-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
--
-- GENERATED by echo-boundary (boundary.mjs). Do not edit by hand.
--
-- This module certifies an @boundary encoding-faithfulness verdict for a
-- concrete host-value -> integer-code table, by reusing the
-- EchoEncodingFaithfulness framework. It follows the SHAPE of that module's
-- worked Rank / rankCode / rankCode-injective instance.
--
-- Source table (host name -> code):
--   {
--     "NOOP": 0,
--     "ADD": 1,
--     "SUB": 2,
--     "NEGATE": 3,
--     "SWAP": 4,
--     "FLIP": 5,
--     "ROL": 6,
--     "ROR": 7,
--     "AND": 8,
--     "OR": 9,
--     "XOR": 10,
--     "MUL": 11,
--     "DIV": 12,
--     "IFZERO": 13,
--     "IFPOS": 14,
--     "LOOP": 15,
--     "PUSH": 16,
--     "POP": 17,
--     "LOAD": 18,
--     "STORE": 19,
--     "CALL": 20,
--     "SEND": 21,
--     "RECV": 22
--   }

module VmInstructionBoundary where

open import Echo                   using (Echo)
open import EchoImageFactorization using (Injective)
open import EchoEncodingFaithfulness using (Encoding; module EncodingTheorems)

open import Data.Nat.Base         using (ℕ)
open import Data.Product.Base     using (Σ; _,_; _×_; proj₁)
open import Relation.Binary.PropositionalEquality
                                  using (_≡_; _≢_; refl)
open import Relation.Nullary      using (¬_)


-- The host-side enumerated value (one constructor per table name).
--   c0 = NOOP
--   c1 = ADD
--   c2 = SUB
--   c3 = NEGATE
--   c4 = SWAP
--   c5 = FLIP
--   c6 = ROL
--   c7 = ROR
--   c8 = AND
--   c9 = OR
--   c10 = XOR
--   c11 = MUL
--   c12 = DIV
--   c13 = IFZERO
--   c14 = IFPOS
--   c15 = LOOP
--   c16 = PUSH
--   c17 = POP
--   c18 = LOAD
--   c19 = STORE
--   c20 = CALL
--   c21 = SEND
--   c22 = RECV
data Host : Set where
  c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18 c19 c20 c21 c22 : Host

-- The integer code the pure kernel computes on.
code : Host → ℕ
code c0  = 0
code c1  = 1
code c2  = 2
code c3  = 3
code c4  = 4
code c5  = 5
code c6  = 6
code c7  = 7
code c8  = 8
code c9  = 9
code c10 = 10
code c11 = 11
code c12 = 12
code c13 = 13
code c14 = 14
code c15 = 15
code c16 = 16
code c17 = 17
code c18 = 18
code c19 = 19
code c20 = 20
code c21 = 21
code c22 = 22

-- Injectivity by exhaustive case analysis. The codes are literal
-- numerals, so listing the diagonal refl clauses is enough: Agda's
-- coverage checker discharges the off-diagonal pairs as absurd
-- numeral equalities (mirrors rankCode-injective).
code-injective : Injective code
code-injective {c0}  {c0}  _ = refl
code-injective {c1}  {c1}  _ = refl
code-injective {c2}  {c2}  _ = refl
code-injective {c3}  {c3}  _ = refl
code-injective {c4}  {c4}  _ = refl
code-injective {c5}  {c5}  _ = refl
code-injective {c6}  {c6}  _ = refl
code-injective {c7}  {c7}  _ = refl
code-injective {c8}  {c8}  _ = refl
code-injective {c9}  {c9}  _ = refl
code-injective {c10} {c10} _ = refl
code-injective {c11} {c11} _ = refl
code-injective {c12} {c12} _ = refl
code-injective {c13} {c13} _ = refl
code-injective {c14} {c14} _ = refl
code-injective {c15} {c15} _ = refl
code-injective {c16} {c16} _ = refl
code-injective {c17} {c17} _ = refl
code-injective {c18} {c18} _ = refl
code-injective {c19} {c19} _ = refl
code-injective {c20} {c20} _ = refl
code-injective {c21} {c21} _ = refl
code-injective {c22} {c22} _ = refl

encoding : Encoding
encoding = record
  { Source = Host
  ; Code   = ℕ
  ; enc    = code
  }

-- Re-export the lossless-half headline, instantiated and proved:
-- every integer code determines its host value uniquely.
module Theorems = EncodingTheorems encoding

boundary-lossless :
  (i : ℕ) (e₁ e₂ : Echo code i) → proj₁ e₁ ≡ proj₁ e₂
boundary-lossless = Theorems.encoding-lossless code-injective

