(* SPDX-License-Identifier: PMPL-1.0-or-later *)
(* SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell *)

(** OpenCL C kernel emitter (MVP). Output validates with [clang -cc1
    -triple spir64 -xcl] or any conformant OpenCL implementation. *)

open Ast

exception Cl_unsupported of string
let unsupported m = raise (Cl_unsupported m)

let scalar_of_type_name = function
  | "Int" -> "int" | "Float" -> "float" | "Bool" -> "bool"
  | n -> unsupported ("type not allowed in OpenCL kernel: " ^ n)

let rec scalar_of (te : type_expr) : string =
  match te with
  | TyCon id -> scalar_of_type_name id.name
  | TyOwn t | TyRef t | TyMut t -> scalar_of t
  | _ -> unsupported "complex type not allowed"

let array_element (te : type_expr) : string =
  let rec strip = function
    | TyOwn t | TyRef t | TyMut t -> strip t
    | t -> t
  in
  match strip te with
  | TyApp (id, [TyArg inner]) when id.name = "Array" -> scalar_of inner
  | _ -> unsupported "expected Array[Int|Float] for kernel buffer"

let access_qual = function
  | Some Mut -> ""              (* read+write *)
  | _        -> "const "        (* read-only *)

let rec gen_expr (e : expr) : string =
  match e with
  | ExprLit lit -> gen_lit lit
  | ExprVar id -> id.name
  | ExprBinary (a, op, b) ->
      let s = match op with
        | OpAdd -> "+" | OpSub -> "-" | OpMul -> "*" | OpDiv -> "/" | OpMod -> "%"
        | OpEq  -> "==" | OpNe -> "!="
        | OpLt  -> "<" | OpLe -> "<=" | OpGt -> ">" | OpGe -> ">="
        | OpAnd -> "&&" | OpOr -> "||"
        | OpBitAnd -> "&" | OpBitOr -> "|" | OpBitXor -> "^"
        | OpShl -> "<<" | OpShr -> ">>"
        | OpConcat -> unsupported "concat not supported"
      in
      "(" ^ gen_expr a ^ " " ^ s ^ " " ^ gen_expr b ^ ")"
  | ExprUnary (OpNeg, x) -> "(-" ^ gen_expr x ^ ")"
  | ExprUnary (OpNot, x) -> "(!" ^ gen_expr x ^ ")"
  | ExprUnary (OpBitNot, x) -> "(~" ^ gen_expr x ^ ")"
  | ExprUnary _ -> unsupported "unary op not supported"
  | ExprIf { ei_cond; ei_then; ei_else } ->
      let f = match ei_else with Some e -> gen_expr e | None -> "0" in
      Printf.sprintf "(%s ? %s : %s)" (gen_expr ei_cond) (gen_expr ei_then) f
  | ExprIndex (a, i) -> Printf.sprintf "%s[%s]" (gen_expr a) (gen_expr i)
  | ExprApp (callee, args) ->
      let name = match callee with ExprVar id -> id.name | _ -> unsupported "indirect call" in
      let known = ["sin"; "cos"; "tan"; "sqrt"; "exp"; "log"; "pow";
                   "fabs"; "floor"; "ceil"; "min"; "max"; "tanh"] in
      if not (List.mem name known) then
        unsupported ("call to non-builtin in OpenCL kernel: " ^ name);
      Printf.sprintf "%s(%s)" name (String.concat ", " (List.map gen_expr args))
  | ExprSpan (inner, _) -> gen_expr inner
  | _ -> unsupported "expression form not supported"

and gen_lit = function
  | LitInt (n, _) -> string_of_int n
  | LitFloat (f, _) ->
      let s = string_of_float f in
      let s = if String.length s > 0 && s.[String.length s - 1] = '.' then s ^ "0" else s in
      s ^ "f"
  | LitBool (true, _) -> "true"
  | LitBool (false, _) -> "false"
  | _ -> unsupported "literal form not supported"

let rec gen_stmt (s : stmt) : string =
  match s with
  | StmtLet { sl_pat = PatVar id; sl_value; sl_ty; _ } ->
      let ty = match sl_ty with Some t -> scalar_of t | None -> "int" in
      Printf.sprintf "%s %s = %s;" ty id.name (gen_expr sl_value)
  | StmtLet _ -> unsupported "destructuring let"
  | StmtAssign (lhs, op, rhs) ->
      let s = match op with
        | AssignEq -> "=" | AssignAdd -> "+=" | AssignSub -> "-="
        | AssignMul -> "*=" | AssignDiv -> "/=" in
      Printf.sprintf "%s %s %s;" (gen_expr lhs) s (gen_expr rhs)
  | StmtExpr e -> gen_expr e ^ ";"
  | StmtWhile (c, b) ->
      Printf.sprintf "while (%s) { %s }" (gen_expr c)
        (String.concat " " (List.map gen_stmt b.blk_stmts))
  | StmtFor _ -> unsupported "for-in"

let pick_kernel (program : program) : fn_decl =
  let fns = List.filter_map (function TopFn fd -> Some fd | _ -> None) program.prog_decls in
  match List.find_opt (fun fd -> fd.fd_name.name = "kernel") fns with
  | Some fd -> fd
  | None -> match fns with fd :: _ -> fd | [] -> unsupported "no function found"

let generate (program : program) (_symbols : Symbol.t) : string =
  let buf = Buffer.create 1024 in
  Buffer.add_string buf "// Generated by AffineScript compiler (OpenCL C)\n";
  Buffer.add_string buf "// SPDX-License-Identifier: PMPL-1.0-or-later\n\n";
  let fd = pick_kernel program in
  let idx = match fd.fd_params with first :: _ -> first.p_name.name | _ -> "i" in
  let bufs = match fd.fd_params with _ :: rest -> rest | [] -> [] in
  let buf_decls = List.map (fun (p : param) ->
    Printf.sprintf "__global %s%s *%s"
      (access_qual p.p_ownership) (array_element p.p_ty) p.p_name.name
  ) bufs in
  Buffer.add_string buf
    (Printf.sprintf "__kernel void %s(%s) {\n" fd.fd_name.name
       (String.concat ", " buf_decls));
  Buffer.add_string buf
    (Printf.sprintf "  int %s = (int)get_global_id(0);\n" idx);
  (match fd.fd_body with
   | FnExpr e ->
       Buffer.add_string buf (Printf.sprintf "  (void)(%s);\n" (gen_expr e))
   | FnBlock b ->
       List.iter (fun s -> Buffer.add_string buf ("  " ^ gen_stmt s ^ "\n")) b.blk_stmts;
       (match b.blk_expr with
        | Some e -> Buffer.add_string buf (Printf.sprintf "  (void)(%s);\n" (gen_expr e))
        | None -> ()));
  Buffer.add_string buf "}\n";
  Buffer.contents buf

let codegen_opencl (program : program) (symbols : Symbol.t) : (string, string) result =
  try Ok (generate program symbols)
  with
  | Cl_unsupported m -> Error ("OpenCL backend: " ^ m)
  | Failure m        -> Error ("OpenCL codegen error: " ^ m)
  | e                -> Error ("OpenCL codegen error: " ^ Printexc.to_string e)
