{-# OPTIONS --safe --without-K #-}
-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
--
-- GENERATED by echo-boundary (boundary.mjs). Do not edit by hand.
--
-- This module certifies an @boundary encoding-faithfulness verdict for a
-- concrete host-value -> integer-code table, by reusing the
-- EchoEncodingFaithfulness framework. It follows the SHAPE of that module's
-- worked Rank / rankCode / rankCode-injective instance.
--
-- Source table (host name -> code):
--   {
--     "Tier0": 0,
--     "Tier1": 1,
--     "Tier2": 2,
--     "Tier3": 3,
--     "Tier4": 4,
--     "UnknownTier": 0
--   }

module PuzzleFormatTierBoundary where

open import Echo                   using (Echo)
open import EchoImageFactorization using (Injective)
open import EchoEncodingFaithfulness using (Encoding; module EncodingTheorems)

open import Data.Nat.Base         using (ℕ)
open import Data.Product.Base     using (Σ; _,_; _×_; proj₁)
open import Relation.Binary.PropositionalEquality
                                  using (_≡_; _≢_; refl)
open import Relation.Nullary      using (¬_)


-- The host-side enumerated value (one constructor per table name).
--   c0 = Tier0
--   c1 = Tier1
--   c2 = Tier2
--   c3 = Tier3
--   c4 = Tier4
--   c5 = UnknownTier   (out-of-band / clamp entry)
data Host : Set where
  c0 c1 c2 c3 c4 c5 : Host

-- The integer code the pure kernel computes on.
code : Host → ℕ
code c0 = 0
code c1 = 1
code c2 = 2
code c3 = 3
code c4 = 4
code c5 = 0

encoding : Encoding
encoding = record
  { Source = Host
  ; Code   = ℕ
  ; enc    = code
  }

module Theorems = EncodingTheorems encoding

-- The collision, as data: two distinct host values collapse onto the
-- same code 0.
--   c0 = Tier0
--   c5 = UnknownTier  (out-of-band / clamp)
-- Distinctness is constructor disjointness; the shared code is refl.
c0≢c5 : c0 ≢ c5
c0≢c5 ()

collision : c0 ≢ c5 × code c0 ≡ code c5
collision = c0≢c5 , refl

-- THE VERDICT, certified: the boundary exhibits controlled loss.
-- The colliding fibre admits NO section -- there is no pure
-- decode : ℕ → Host recovering the host value from its code,
-- because two distinct host values share one code. The lost
-- distinction is named and localised at code 0.
boundary-controlled-loss :
  ¬ Σ (ℕ → Host) (λ decode → ∀ x → decode (code x) ≡ x)
boundary-controlled-loss =
  Theorems.encoding-collision⇒no-section
    c0 c5
    c0≢c5
    refl

