{-# OPTIONS --safe --without-K #-}
-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
--
-- GENERATED by echo-boundary (boundary.mjs). Do not edit by hand.
--
-- This module certifies an @boundary encoding-faithfulness verdict for a
-- concrete host-value -> integer-code table, by reusing the
-- EchoEncodingFaithfulness framework. It follows the SHAPE of that module's
-- worked Rank / rankCode / rankCode-injective instance.
--
-- Source table (host name -> code):
--   {
--     "Practitioner": 1,
--     "Professional": 2,
--     "Expert": 3,
--     "Architect": 4,
--     "Sovereign": 5
--   }

module QCertificationsBoundary where

open import Echo                   using (Echo)
open import EchoImageFactorization using (Injective)
open import EchoEncodingFaithfulness using (Encoding; module EncodingTheorems)

open import Data.Nat.Base         using (ℕ)
open import Data.Product.Base     using (Σ; _,_; _×_; proj₁)
open import Relation.Binary.PropositionalEquality
                                  using (_≡_; _≢_; refl)
open import Relation.Nullary      using (¬_)


-- The host-side enumerated value (one constructor per table name).
--   c0 = Practitioner
--   c1 = Professional
--   c2 = Expert
--   c3 = Architect
--   c4 = Sovereign
data Host : Set where
  c0 c1 c2 c3 c4 : Host

-- The integer code the pure kernel computes on.
code : Host → ℕ
code c0 = 1
code c1 = 2
code c2 = 3
code c3 = 4
code c4 = 5

-- Injectivity by exhaustive case analysis. The codes are literal
-- numerals, so listing the diagonal refl clauses is enough: Agda's
-- coverage checker discharges the off-diagonal pairs as absurd
-- numeral equalities (mirrors rankCode-injective).
code-injective : Injective code
code-injective {c0} {c0} _ = refl
code-injective {c1} {c1} _ = refl
code-injective {c2} {c2} _ = refl
code-injective {c3} {c3} _ = refl
code-injective {c4} {c4} _ = refl

encoding : Encoding
encoding = record
  { Source = Host
  ; Code   = ℕ
  ; enc    = code
  }

-- Re-export the lossless-half headline, instantiated and proved:
-- every integer code determines its host value uniquely.
module Theorems = EncodingTheorems encoding

boundary-lossless :
  (i : ℕ) (e₁ e₂ : Echo code i) → proj₁ e₁ ≡ proj₁ e₂
boundary-lossless = Theorems.encoding-lossless code-injective

