{-# OPTIONS --safe --without-K #-}
-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
--
-- GENERATED by echo-boundary (boundary.mjs). Do not edit by hand.
--
-- This module certifies an @boundary encoding-faithfulness verdict for a
-- concrete host-value -> integer-code table, by reusing the
-- EchoEncodingFaithfulness framework. It follows the SHAPE of that module's
-- worked Rank / rankCode / rankCode-injective instance.
--
-- Source table (host name -> code):
--   {
--     "Laptop": 0,
--     "Desktop": 1,
--     "Server": 2,
--     "Router": 3,
--     "Switch": 4,
--     "Firewall": 5,
--     "Camera": 6,
--     "AccessPoint": 7,
--     "PatchPanel": 8,
--     "PowerSupply": 9,
--     "PhoneSystem": 10,
--     "FibreHub": 11
--   }

module DeviceTypeBoundary where

open import Echo                   using (Echo)
open import EchoImageFactorization using (Injective)
open import EchoEncodingFaithfulness using (Encoding; module EncodingTheorems)

open import Data.Nat.Base         using (ℕ)
open import Data.Product.Base     using (Σ; _,_; _×_; proj₁)
open import Relation.Binary.PropositionalEquality
                                  using (_≡_; _≢_; refl)
open import Relation.Nullary      using (¬_)


-- The host-side enumerated value (one constructor per table name).
--   c0 = Laptop
--   c1 = Desktop
--   c2 = Server
--   c3 = Router
--   c4 = Switch
--   c5 = Firewall
--   c6 = Camera
--   c7 = AccessPoint
--   c8 = PatchPanel
--   c9 = PowerSupply
--   c10 = PhoneSystem
--   c11 = FibreHub
data Host : Set where
  c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 : Host

-- The integer code the pure kernel computes on.
code : Host → ℕ
code c0  = 0
code c1  = 1
code c2  = 2
code c3  = 3
code c4  = 4
code c5  = 5
code c6  = 6
code c7  = 7
code c8  = 8
code c9  = 9
code c10 = 10
code c11 = 11

-- Injectivity by exhaustive case analysis. The codes are literal
-- numerals, so listing the diagonal refl clauses is enough: Agda's
-- coverage checker discharges the off-diagonal pairs as absurd
-- numeral equalities (mirrors rankCode-injective).
code-injective : Injective code
code-injective {c0}  {c0}  _ = refl
code-injective {c1}  {c1}  _ = refl
code-injective {c2}  {c2}  _ = refl
code-injective {c3}  {c3}  _ = refl
code-injective {c4}  {c4}  _ = refl
code-injective {c5}  {c5}  _ = refl
code-injective {c6}  {c6}  _ = refl
code-injective {c7}  {c7}  _ = refl
code-injective {c8}  {c8}  _ = refl
code-injective {c9}  {c9}  _ = refl
code-injective {c10} {c10} _ = refl
code-injective {c11} {c11} _ = refl

encoding : Encoding
encoding = record
  { Source = Host
  ; Code   = ℕ
  ; enc    = code
  }

-- Re-export the lossless-half headline, instantiated and proved:
-- every integer code determines its host value uniquely.
module Theorems = EncodingTheorems encoding

boundary-lossless :
  (i : ℕ) (e₁ e₂ : Echo code i) → proj₁ e₁ ≡ proj₁ e₂
boundary-lossless = Theorems.encoding-lossless code-injective

