(* SPDX-License-Identifier: MPL-2.0 *)
(* SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell *)

let module_name_of_path path =
  let base = Filename.basename path in
  let stem =
    try Filename.chop_extension base
    with Invalid_argument _ -> base
  in
  if String.length stem = 0 then "Module"
  else
    String.make 1 (Char.uppercase_ascii stem.[0])
    ^ String.sub stem 1 (String.length stem - 1)

let bullet_for_finding (f : Scanner.finding) =
  Printf.sprintf
    "//   - [%s] line %d: %s\n//       %s"
    (Scanner.kind_to_label f.kind)
    f.line
    (Scanner.kind_to_guidance f.kind)
    f.excerpt

let summarise_findings findings =
  let buf = Buffer.create 256 in
  if findings = [] then begin
    Buffer.add_string buf
      "// MIGRATE: scanner found no Phase-1 anti-patterns. A clean .res\n";
    Buffer.add_string buf
      "//          surface does not mean the port is mechanical —\n";
    Buffer.add_string buf
      "//          re-decomposition still applies (see PILOT.md upstream).";
    Buffer.contents buf
  end else begin
    Buffer.add_string buf
      (Printf.sprintf
         "// MIGRATE: %d migration consideration%s detected. Each entry below\n"
         (List.length findings)
         (if List.length findings = 1 then "" else "s"));
    Buffer.add_string buf
      "//          names the pattern, source line, and the AffineScript\n";
    Buffer.add_string buf
      "//          answer to consider before porting.";
    List.iter
      (fun f ->
        Buffer.add_char buf '\n';
        Buffer.add_string buf (bullet_for_finding f))
      findings;
    Buffer.contents buf
  end

let quote_block source =
  let lines = String.split_on_char '\n' source in
  let quoted = List.map (fun l -> "   " ^ l) lines in
  let buf = Buffer.create (String.length source + 64) in
  Buffer.add_string buf
    "/* ORIGINAL RESCRIPT — retained for reference; delete once port lands.\n";
  Buffer.add_string buf (String.concat "\n" quoted);
  Buffer.add_string buf "\n*/";
  Buffer.contents buf

let emit ~module_name ~source_path ~source ~findings =
  let buf = Buffer.create 4096 in
  let add s = Buffer.add_string buf s in
  add "// SPDX-License-Identifier: MPL-2.0\n";
  add "// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell\n";
  add "//\n";
  add (Printf.sprintf
         "// Generated by tools/res-to-affine from %s\n" source_path);
  add "// This is a Phase-1 SKELETON. It does NOT compile. Bodies are TODO.\n";
  add "// See tools/res-to-affine/README.md for the migration workflow.\n";
  add "//\n";
  add (summarise_findings findings);
  add "\n\n";
  add (Printf.sprintf "module %s\n\n" module_name);
  add "// TODO: re-decompose the original into focused AffineScript modules.\n";
  add "//       Effect-track each signature, replace mutable state with affine\n";
  add "//       records, and lift Result/Validation to fail-paths.\n";
  add "\n";
  add (quote_block source);
  add "\n";
  Buffer.contents buf
